#
###################################
# Site wide configuration
####################################
#
title: Jmunene
email: munenegicovi@gmail.com
description: Data Engineer - Analytics/R/Tableau/XLSForms/SurveyToGo.
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          #Africa/Kenya
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jonathan Munene
  avatar: jmunene.jpg
  job: "Data Engineer"
  bio: "Lead Consultant - SwissPeaks East Africa [R, Shiny, Tableau, XLSForms, Stata,SPSS, ODK, SurveyToGo, Data Science & Machine Learning]."
  email: munenegicovi@gmail.com
  disqus-shortname:
  twitter: mgicovi
  facebook: munene.gicovi
  google:
    plus: https://plus.google.com/u/0/117400962805501248258
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jmunene
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: jonathan-munene-a46bb924
  skype: muneneg
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
